[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "ALLOW-FROM *"
    Content-Security-Policy-Report-Only = "frame-ancestors *;"
    Content-Security-Policy = """
      default-src 'self' https://*.supabase.co https://*.cardcom.solutions https://secure.cardcom.solutions https://*.leadconnectorhq.com;
      script-src 'self' 'unsafe-inline' 'unsafe-eval';
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: blob: https://*;
      font-src 'self' data:;
      connect-src 'self' https://*.supabase.co https://*.cardcom.solutions https://secure.cardcom.solutions https://api.cardcom.solutions wss://*.supabase.co https://*.leadconnectorhq.com https://services.leadconnectorhq.com;
      frame-src 'self' https://*.cardcom.solutions https://secure.cardcom.solutions;
      form-action 'self' https://*.cardcom.solutions https://secure.cardcom.solutions;
      frame-ancestors *;
    """
