[build]
  command = "CI=false NODE_ENV=production npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  CI = "false"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# הגדרת Background Function ספציפית ל-webhook processor
[functions."process-webhooks"]
  background = true
  included_files = ["netlify/functions/process-webhooks/*"]

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = '''
      default-src 'self' https://*.supabase.co https://*.cardcom.solutions https://secure.cardcom.solutions https://*.leadconnectorhq.com https://fonts.gstatic.com;
      script-src 'self' 'unsafe-inline' 'unsafe-eval';
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: blob: https://*;
      font-src 'self' data: https://fonts.gstatic.com;
      connect-src 'self' https://*.supabase.co https://*.cardcom.solutions https://secure.cardcom.solutions https://api.cardcom.solutions wss://*.supabase.co https://*.leadconnectorhq.com https://services.leadconnectorhq.com;
      frame-src 'self' https://*.cardcom.solutions https://secure.cardcom.solutions;
      form-action 'self' https://*.cardcom.solutions https://secure.cardcom.solutions;
      frame-ancestors *;
    '''
    Content-Security-Policy-Report-Only = "frame-ancestors *"
    X-Frame-Options = "ALLOW-FROM *"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
