[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  SUPABASE_URL = "https://nebyatzjlumpqylpjcap.supabase.co"
  SUPABASE_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5lYnlhdHpqbHVtcHF5bHBqY2FwIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcwMjQ1NzUwMiwiZXhwIjoyMDE4MDMzNTAyfQ.Nq0vPx5LXrVuV5kXmJMXCGUGAWzVfuqkbFZiVQOUGYM"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self' https://*.supabase.co https://*.cardcom.solutions https://secure.cardcom.solutions;
      script-src 'self' 'unsafe-inline' 'unsafe-eval';
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: blob: https://*;
      font-src 'self' data:;
      connect-src 'self' https://*.supabase.co https://*.cardcom.solutions https://secure.cardcom.solutions https://api.cardcom.solutions wss://*.supabase.co;
      frame-src 'self' https://*.cardcom.solutions https://secure.cardcom.solutions;
      form-action 'self' https://*.cardcom.solutions https://secure.cardcom.solutions;
    """
